# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7230894a059b98896d9915df94700733e46ce25e534a4c985b7025f4ab1d211e2632bc4263ac6f80ae06a994e19e47c1d36d3ae066e3c7f964b21a71ad197e7b
  postmark_api_key: <%= ENV["POSTMARK_KEY"] %>
  asset_host: <%= ENV["ASSET_HOST"] %>
  stripe_secret_key: 7230894a059b98896d9915df94700733e46ce25e534a4c985b7025f4ab1d211e2632bc4263ac6f80ae06a994e19e47c1d36d3ae066e3c7f964b21a71ad197e7b <%#= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: 7230894a059b98896d9915df94700733e46ce25e534a4c985b7025f4ab1d211e2632bc4263ac6f80ae06a994e19e47c1d36d3ae066e3c7f964b21a71ad197e7b <%#= ENV["STRIPE_PUBLISHABLE_KEY"] %>

test:
  secret_key_base: 826484440fa2e47cf3fcebb7c8b1754f108ca7c1f2701ddea4f5d5bd6a0e5319cb70cabbb920f0288b0c95cb23f835f1b8ecbd0b6e526e15b0501891b965f6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_key: <%= ENV["POSTMARK_KEY"] %>
  asset_host: <%= ENV["ASSET_HOST"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_key: <%= ENV["POSTMARK_KEY"] %>
  asset_host: <%= ENV["ASSET_HOST"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  
