require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Physician::DiagnosticsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Diagnostic. As you add validations to Diagnostic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Physician::DiagnosticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all diagnostics as @diagnostics" do
      diagnostic = Diagnostic.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:diagnostics)).to eq([diagnostic])
    end
  end

  describe "GET #show" do
    it "assigns the requested physician_diagnostic as @physician_diagnostic" do
      diagnostic = Diagnostic.create! valid_attributes
      get :show, {:id => diagnostic.to_param}, valid_session
      expect(assigns(:physician_diagnostic)).to eq(diagnostic)
    end
  end

  describe "GET #new" do
    it "assigns a new physician_diagnostic as @physician_diagnostic" do
      get :new, {}, valid_session
      expect(assigns(:physician_diagnostic)).to be_a_new(Diagnostic)
    end
  end

  describe "GET #edit" do
    it "assigns the requested physician_diagnostic as @physician_diagnostic" do
      diagnostic = Diagnostic.create! valid_attributes
      get :edit, {:id => diagnostic.to_param}, valid_session
      expect(assigns(:physician_diagnostic)).to eq(diagnostic)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Diagnostic" do
        expect {
          post :create, {:physician_diagnostic => valid_attributes}, valid_session
        }.to change(Diagnostic, :count).by(1)
      end

      it "assigns a newly created physician_diagnostic as @physician_diagnostic" do
        post :create, {:physician_diagnostic => valid_attributes}, valid_session
        expect(assigns(:physician_diagnostic)).to be_a(Diagnostic)
        expect(assigns(:physician_diagnostic)).to be_persisted
      end

      it "redirects to the created physician_diagnostic" do
        post :create, {:physician_diagnostic => valid_attributes}, valid_session
        expect(response).to redirect_to(Diagnostic.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved physician_diagnostic as @physician_diagnostic" do
        post :create, {:physician_diagnostic => invalid_attributes}, valid_session
        expect(assigns(:physician_diagnostic)).to be_a_new(Diagnostic)
      end

      it "re-renders the 'new' template" do
        post :create, {:physician_diagnostic => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested physician_diagnostic" do
        diagnostic = Diagnostic.create! valid_attributes
        put :update, {:id => diagnostic.to_param, :physician_diagnostic => new_attributes}, valid_session
        diagnostic.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested physician_diagnostic as @physician_diagnostic" do
        diagnostic = Diagnostic.create! valid_attributes
        put :update, {:id => diagnostic.to_param, :physician_diagnostic => valid_attributes}, valid_session
        expect(assigns(:physician_diagnostic)).to eq(diagnostic)
      end

      it "redirects to the physician_diagnostic" do
        diagnostic = Diagnostic.create! valid_attributes
        put :update, {:id => diagnostic.to_param, :physician_diagnostic => valid_attributes}, valid_session
        expect(response).to redirect_to(diagnostic)
      end
    end

    context "with invalid params" do
      it "assigns the physician_diagnostic as @physician_diagnostic" do
        diagnostic = Diagnostic.create! valid_attributes
        put :update, {:id => diagnostic.to_param, :physician_diagnostic => invalid_attributes}, valid_session
        expect(assigns(:physician_diagnostic)).to eq(diagnostic)
      end

      it "re-renders the 'edit' template" do
        diagnostic = Diagnostic.create! valid_attributes
        put :update, {:id => diagnostic.to_param, :physician_diagnostic => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested physician_diagnostic" do
      diagnostic = Diagnostic.create! valid_attributes
      expect {
        delete :destroy, {:id => diagnostic.to_param}, valid_session
      }.to change(Diagnostic, :count).by(-1)
    end

    it "redirects to the diagnostics list" do
      diagnostic = Diagnostic.create! valid_attributes
      delete :destroy, {:id => diagnostic.to_param}, valid_session
      expect(response).to redirect_to(diagnostics_url)
    end
  end

end
